#! /usr/bin/env python3.6

import sys, common, subprocess

def parse_args():
    import argparse
    p = argparse.ArgumentParser()
    p.add_argument('iters', type=int)
    p.add_argument('cmd', nargs='*')
    args = vars(p.parse_args())
    return args['iters'], args['cmd']


if __name__ == "__main__":
    iters, cmd = parse_args()
    if len(cmd) == 0:
        sys.exit(0)

    try:
        for i in range(iters):
            subprocess.call(cmd)
    except KeyboardInterrupt:
        pass