#! /usr/bin/env python3.6

import sys, subprocess, time
from common import align_width

def do_one():
    data_line = subprocess.check_output('free -m', shell=True).decode('utf8').strip().split('\n')[1]
    total, used, free = list(map(int, data_line.split()[1:4]))

    # with open('/proc/meminfo') as f:
    #     lines = f.readlines()
    # def get_mem_mb(line):
    #     return int(lines[line].split()[1]) // 1024
    # total = get_mem_mb(0)
    # free = get_mem_mb(1)
    # buff = get_mem_mb(3)
    # cache = get_mem_mb(4)
    # used = total - free - buff - cache


    # align_width([
    #     ['Used', '{} / {} MB ({:.0%})'.format(used, total, used / total)],
    #     # ['Free', '%d MB' % free]
    # ])
    print('\t{} / {} MB ({:.0%})'.format(used, total, used / total))

def go_up(nlines):
    up_line = "\033[F"
    print(up_line * nlines, end='')

def do_forever():
    print()
    do_one()
    print()
    try:
        while True:
            go_up(2)
            do_one()
            print()
            time.sleep(1)
    except KeyboardInterrupt:
        pass

if __name__ == "__main__":
    do_forever()